language: cpp
compiler: clang
os: osx
osx_image: xcode9.1

before_install:
- brew install ninja || true
- brew install boost || true

script:
- mkdir build
- cd build
- cmake ..
- make
- test/unittest
