language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja boost || true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo cmake_ver='3.10.1' boost_ver='1.66.0' ./ubuntu_install_build_deps.sh;
    fi

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      compiler: clang
      osx_image: xcode9.1

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
  - make
  - test/unittest
